### ISSUE TITLE
[RFC] More discoverable identifiers for the :LspInstall, :LspUninstall commands

### ISSUE THREAD

**Issue by williamboman** [williamboman/nvim-lsp-installer#177]
## Background
The `:LspInstall` and `:LspUninstall` commands currently only allow providing the lspconfig server names. This can be somewhat confusing for people who have not spent any time on LSP development - for example a Python LSP can be installed via `:LspInstall pyright`, `:LspInstall pylsp`, and `:LspInstall jedi_language_server`. Unless you are familiar with these Python LSPs it's 1) difficult to discover these in the first place (you may get lucky by typing `py<Tab>`), and 2) knowing which one to choose.

### 1. Prefix server names with a more discoverable name

Each server may be associated with one or more constructs that are more accessible to the average user. Arguably, the dominant construct in this context would be which language/framework/library the LSP targets. This mapping is already provided in the [README](https://github.com/williamboman/nvim-lsp-installer#available-lsps).

These prefixes will only be available for autocompletion in the command line. Calls to the underlying Lua APIs would not respect the prefix, and will return error should a prefix be included. In order to reduce noise, the server's true names will no longer be available for autocompletion in the command line - but they will still be considered valid inputs.

**Examples**
- `:LspInstall python:pylsp@some-version`
- `:LspInstall python:pylsp`
- `:LspInstall python:pyright`
- `:LspInstall vue:volar`

**Considerations to be made**
- Should there be a limit to how many prefixes a server may have? Are there any cases where it makes sense to have more than one?
- Should autocompletion in the command line still include the server's true names?

-----

### 2. Introduce a new :LspInstallLanguage command

A new `:LspInstallLanguage` command could allow us to have two neatly separated commands for installing a server by using a different identifier. We could also use this command to impose a recommended, default, server per language. In the case where there are more than one LSP per language, this recommended server could either be automatically chosen, or we could prompt the user which one to install (and have the prompt default to the recommended one).

**Examples**
- `:LspInstallLanguage python`
- `:LspInstallLanguage graphql`
- `:LspInstallLanguage vue`

With prompt:
```
:LspInstallLanguage python
Please choose which server you want to install.
(1) pyright (recommended), [2] pylsp, (3) jedi_language_server:
```

We could also use the prompt to signal servers that are unstable, for example if the server has a questionable implementation of the LSP spec. This could potentially help managing expectations and reducing volume of related support issues.

```
:LspInstallLanguage csharp
Please choose which server you want to install.
(1) omnisharp (unstable)
```

## Resolve by
25th October 2021

**Comment by shaunsingh** [comment]
> Ping @shaunsingh

LGTM. If there are multiple options, maybe have a recommended default server? (e.g. pyright is pretty much accepted as the goto python server)

**Comment by williamboman** [comment]
> Would you consider using Telescope for this? or do you want to keep it simpler/independent?

For sure an independent thing, sticking to first principles. If someone wants to hook it into Telescope that should be totally doable using this plugin's Lua APIs

**Comment by williamboman** [comment]
So after letting this brew for a while I think the best experience would be what @isaif suggested, with the `:LspInstall` command behaving like today. We'd simply just extend its completion with virtual entries ("aliases") that would map to one or more actual servers. This would for example look like this, using `confirm()` to prompt the user for a selection:

```
:LspInstall python
Multiple options are available, please select which server you want to install:
(1) pyright, (2) pylsp, (3) jedi_language_server:
```

These aliases would only be available in the command-line as an autocompletion item. Calling the Lua APIs (e.g. `.install_server("python")`) would render errors.

**Comment by williamboman** [comment]
In terms of how to implement this. I'm figuring that there should be a new requirement that each nvim-lsp-installer server instance must provide a list of `languages` as a property. This will in most cases just be a one-item list with a single language, like `languages = { "python" }`. This property will be used by the metadata autogen script to create look-up tables for fast access and ease of governance.

By having each server provide a list of languages we need to avoid these languages from carrying over to the autocompletion list as it would only pollute it in most cases. I'm thinking we could apply some intuitive heuristics, for example _excluding_ language servers that fulfill the following conditions:

1) The server name has a similar name as its language. The similarity criterion can be whatever, but I figure a simple `language.indexOf(serverName) == 1` would suffice. The rationale here is that adding a virtual entry would not really help users discover it.
2) The associated languages are only related to this one server.

**Comment by williamboman** [comment]
The above spec produces the following. Seems somewhat decent?

```lua
-- THIS FILE IS GENERATED. DO NOT EDIT MANUALLY.
-- stylua: ignore start
return {
  ["c++"] = { "clangd" },
  csharp = { "omnisharp" },
  d = { "serve_d" },
  eslint = { "eslint", "eslintls" },
  fortran = { "fortls" },
  haskell = { "hls" },
  java = { "jdtls" },
  javascript = { "rome", "tsserver" },
  latex = { "ltex", "texlab" },
  lua = { "sumneko_lua" },
  php = { "intelephense", "phpactor" },
  python = { "jedi_language_server", "pylsp", "pyright" },
  ruby = { "solargraph" },
  sql = { "sqlls", "sqls" },
  terraform = { "terraformls", "tflint" },
  typescript = { "rome", "tsserver" },
  vue = { "volar", "vuels" },
  xml = { "lemminx" },
  zig = { "zls" }
}
```

**Comment by williamboman** [comment]
Opened draft PR in #232, give it a spin and tell me what you think

**Comment by kylo252** [comment]
I'm starting to have second thoughts on the "language" sorting. It feels like drawing a line in the sand on what's considered a language, e.g. `eslint`, `tailwind` and `terraform` have all somehow made it to that list but not `markdown` or `html`.

I think that we should actually stick to "filetypes" as an alternate identifier, for both clarity and correctness.

I'm also wondering why not just re-use this https://github.com/williamboman/nvim-lsp-installer/blob/4afdea2ad3bdd970b0e4fc442de4af41017730ae/lua/nvim-lsp-installer/_generated/filetype_map.lua


I think a simple heuristic to apply is to exclude adding any filetype that shares the same 3 letters with the name of its server. So something like this:

```lua
function M.get_install_completion()
  local filetypes_map = require "nvim-lsp-installer._generated.filetype_map"
  local uncommon_names = {}
  local skipped_filetypes = {}
  for k, v in pairs(filetypes_map) do
    if vim.tbl_count(v) == 1 then
      if not vim.startswith(k, v[1]:sub(1, 3)) then
        table.insert(uncommon_names, k)
      else
        table.insert(skipped_filetypes, k)
      end
    else
      table.insert(uncommon_names, k)
    end
  end
  local servers = require "nvim-lsp-installer.servers"
  local result = {}
  local server_names = servers.get_available_server_names()
  vim.list_extend(result, server_names)
  vim.list_extend(result, uncommon_names)
  table.sort(result)
  print("nrOfFiletypes: " .. vim.tbl_count(filetypes_map))
  print("nrOfUniqueNames: " .. vim.tbl_count(uncommon_names))
  print("completion list length: " .. vim.tbl_count(result))
  -- print("unique names: " .. vim.inspect(uncommon_names))
  -- print("skipped filetypes: " .. vim.inspect(skipped_filetypes))
  print("completion list: " .. vim.inspect(result))
end
```

**Comment by williamboman** [comment]
> I'm starting to have second thoughts on the "language" sorting. It feels like drawing a line in the sand on what's considered a language, e.g. `eslint`, `tailwind` and `terraform` have all somehow made it to that list but not `markdown` or `html`.

Yeah I agree that what constitutes a language is a bit fuzzy perhaps. The way I approached it was to aim for something balanced that would lead to the highest number of "hit rates" in terms of users trying to find it. As for what ends up in that language mapping follows the logic described in https://github.com/williamboman/nvim-lsp-installer/issues/177#issuecomment-955815529, so in the case of `html` it does not show up because there's only one language for "HTML" and it's underlying LSP name happens to be `html`.

I don't think it's too important that we have a perfect mapping here, I think for these purposes something that is "good enough" will suffice (which we can iterate on over time).

> I think that we should actually stick to "filetypes" as an alternate identifier, for both clarity and correctness. I'm also wondering why not just re-use this https://github.com/williamboman/nvim-lsp-installer/blob/4afdea2ad3bdd970b0e4fc442de4af41017730ae/lua/nvim-lsp-installer/_generated/filetype_map.lua

I was thinking about this too but decided to not explore it. Filetypes can often be very esoteric, and while one could argue it would lead to a more correct mapping, I think the resulting UX will be worse. I've attached two screenshots of examples when using filetypes leads to ambiguity and noise. Not to mention certain servers (*couh* tailwind) is registered to a huge amount of filetypes.

I think using a direct filetype mapping could be interesting to allow installing an LSP that is relevant to one's currently open buffer. This could for example be achieved by just entering `:LspInstall`.

<img width="272" alt="Screenshot 2021-11-01 at 14 22 45" src="https://user-images.githubusercontent.com/6705160/139678443-d44669dc-01eb-4e00-bf20-442e2b545e40.png">

<img width="255" alt="Screenshot 2021-11-01 at 14 22 38" src="https://user-images.githubusercontent.com/6705160/139678441-389db342-7371-4130-9029-18c4dc03d0a4.png">

**Comment by kylo252** [comment]
I had forgotten about the case where the server is called, by lspconfig, the same as the filetype. I fixed that in my PR and here's the result.

The algorithm is still pretty simple:

```lua
    for ft, names in pairs(filetype_map) do
        if not has_matching_prefix(ft, names) and not vim.tbl_contains(names, ft) then
            table.insert(uncommon_names, ft)
        else
            table.insert(skipped_filetypes, ft)
        end
    end
```

and I would say the results should be what anyone would expect

https://user-images.githubusercontent.com/59826753/139705063-31e443ec-1c1a-44f7-a2d4-0b5e639768d7.mp4

:

**Comment by williamboman** [comment]
> and I would say the results should be what anyone would expect

Hmm I'm still not convinced. Been playing around with that branch for a while and I have no idea what half the names even are, nor what underlying servers they're mapped to. I think tailwindcss is the culprit for many of these, but it's a general observation.

I think using filetypes as a method to discover LSPs is interesting, but perhaps not as a source for autocompletion. What about allowing `:LspInstall` without any arguments, in which case it'd use the current buffer's (or perhaps all open buffers and make it interactive) filetype.

![Screenshot 2021-11-02 at 13 48 54](https://user-images.githubusercontent.com/6705160/139850092-8d208671-1364-4b3c-859a-af1eb8f43193.png)
![Screenshot 2021-11-02 at 13 49 06](https://user-images.githubusercontent.com/6705160/139850096-8bec4e81-7a86-4630-9008-fd3c6aaf111e.png)
![Screenshot 2021-11-02 at 13 49 23](https://user-images.githubusercontent.com/6705160/139850098-e36b5b1e-fb0b-4396-8af1-18bf622d28e0.png)
![Screenshot 2021-11-02 at 13 51 32](https://user-images.githubusercontent.com/6705160/139850099-527bbb56-8c9a-489a-b560-13690a708f9d.png)

**Comment by williamboman** [comment]
What do you others think?

**Comment by kylo252** [comment]
> Hmm I'm still not convinced. Been playing around with that branch for a while and I have no idea what half the names even are, nor what underlying servers they're mapped to. I think tailwindcss is the culprit for many of these, but it's a general observation.

I only appended the filetypes to the _original_ list of server names, so any additions are purely based on filetypes.

> I think using filetypes as a method to discover LSPs is interesting, but perhaps not as a source for autocompletion. 

I thought that was the whole point? Say a user doesn't know the name of the python server, or maybe they do know, now it doesn't matter anymore

![image](https://user-images.githubusercontent.com/59826753/139904427-31ca1ed5-98a1-40cb-b058-27a278b1c60a.png)

Am I missing something obvious here?

> What about allowing `:LspInstall` without any arguments, in which case it'd use the current buffer's (or perhaps all open buffers and make it interactive) filetype. We already kind of do this in the UI, where relevant LSPs are hoisted in the UI and receive a blue list icon.

I think that could also work, but you need a confirmation in case someone was expecting the UI panel instead. It might also be hard to guess that the command would allow this, so maybe you need a new command `LspInstallBuf`, but that's confusing because it sounds like you're only installing it for that buffer, so you're now stuck picking a descriptive-yet-not-too-long-name.

**Comment by williamboman** [comment]
> I thought that was the whole point? Say a user doesn't know the name of the python server, or maybe they do know, now it doesn't matter anymore

Yep it is! I think the discussion is more about where to source these additional, aliased, entries from. In #232 I went with sourcing these through a new field provided by each server instance, whereas your branch directly uses lspconfig's filetype mapping. After giving both a try I still prefer not using filetypes, for reasons mentioned in my earlier comments. I think using filetypes actually has the opposite effect of adding more ambiguity, not less 😬 . But these are only my opinions, would be interesting to hear what others think before deciding which approach to use.

**Comment by wookayin** [comment]
> but that's confusing because it sounds like you're only installing it for that buffer, so you're now stuck picking a descriptive-yet-not-too-long-name.

How about `:LspInstall <lsp server name>` and either
- `:LspInstallLanguage <language name>`
- `:LspInstallFileType <filetype name>` (filetype name and language name are essentially the same thing, but more indicating it follows the convention used in vim filetypes)
- or `:LspInstall lang:<name>`  

For the last one, we could consider providing completion for all the languages *only if* the prefix `lang:` is typed (`lang:` itself can appear in the first entry of the completion menu with no query), in which case we can have a single command while taking advantage of rich command-line autocompletion (if any).

**Comment by williamboman** [comment]
I really don't want to add more variants of the `:LspInstall` command, I think that'd be solving problems that don't exist. Let's go with #232 for now. If it turns out to be a mess to maintain or if people are still struggling to discover servers we could give other approaches a try (like #233)
