### ISSUE TITLE
GraphQL language server in react

### ISSUE THREAD

**Issue by NICHTJ3** [williamboman/nvim-lsp-installer#18]
This is more of just a question but have you actually managed to use the graphql lsp in a typescript react project? I don't seem to get autocomplete

**Comment by williamboman** [comment]
Hey! Yep. Do you have a `.graphqlrc.yml` properly set up etc?

<img width="930" alt="Screenshot 2021-05-18 at 23 31 16" src="https://user-images.githubusercontent.com/6705160/118726248-59892300-b831-11eb-9923-a5b7a0d6d0b7.png">

**Comment by NICHTJ3** [comment]
I'm using a graphql.config.js file and it works for coc-graphql and vscode graphql so I assume since it's the same language server it would work. Are your dotfiles public?

**Comment by williamboman** [comment]
Could you try updating the plugin version? I pushed https://github.com/williamboman/nvim-lsp-installer/commit/12794b29276949508dcfc37df051ddf1f7278888 yesterday which updates the `root_pattern` to cover all supported graphql-config files.

**Comment by NICHTJ3** [comment]
Still doesn't appear to be working for me and I'm getting this error for both graphql and tsserver
<img width="1435" alt="Screen Shot 2021-05-21 at 10 27 13 AM" src="https://user-images.githubusercontent.com/39316919/119056680-38862500-ba1f-11eb-9e9c-88723119abd4.png">

**Comment by NICHTJ3** [comment]
Out of curiosity though. What does your graphqlrc look like?

**Comment by williamboman** [comment]
> Still doesn't appear to be working for me and I'm getting this error for both graphql and tsserver

What OS & arch are you running? `$ uname -a`

> Out of curiosity though. What does your graphqlrc look like?

```yml
schema: ./src/core/graphql/schema.json
documents:
    - ./src/**/*.tsx
    - ./src/**/*.ts
    - ./src/**/*.graphql
```

**Comment by NICHTJ3** [comment]
```sh
uname -a
# Linux DESKTOP-05I2IK5 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I think the only difference is that I'm pointing to a schema.graphql file but it seams strange that it works with coc-graphql and vscode-graphql

**Comment by NICHTJ3** [comment]
I just switched back over to my old coc config and the issue is still there. I'm thinking it might just be something to do with the graphql lsp

**Comment by NICHTJ3** [comment]
Got it working by just specifying the command and manually installing graphql lsp for some reason it was defaulting to searching for a graphql config in the directory the lsp was installed in even though the root directory was correct 🤷‍♂️
